language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
  - stable
before_script:
  - npm prune
script:
  - npm run test && codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
